local gt = this.getroottable();

if (!("EL_Item_Other" in gt.Const))
{
	gt.Const.EL_Item_Other <- {};
}

gt.Const.EL_Item_Other <- {
	MaxLevelInEventAndCraft = 0,
	MinLevelInEventAndCraft = 10,
	EssenceRankUpNeedFactor = 3,
	EL_NPCEquipment = {
		RankUpMinWorldLevel = 60,
        RankUpChanceFactor = [
            10,
            25,
            25
        ]
	},

	EL_SpecialNamedItem = [
		"legend_armor/chain/legend_armor_hauberk_full_named",
		"legend_armor/cloth/legend_gambeson_named",
		"legend_armor/cloth/legend_tunic_noble_named",
		"legend_armor/named/legend_armor_cloak_emperors",
		"legend_armor/named/legend_armor_cloak_rich",
		"legend_armor/named/legend_armor_named_tabard",
		"legend_armor/plate/legend_armor_leather_brigandine_named",
		"legend_armor/plate/legend_armor_leather_jacket_named",
		"legend_armor/plate/legend_armor_leather_lamellar_heavy_named",
		"legend_armor/plate/legend_armor_leather_studded_jacket_named",
		"legend_armor/plate/legend_armor_plate_full_greaves_named",
		"legend_armor/plate/legend_armor_plate_full_greaves_painted",
		"legend_armor/plate/legend_armor_scale_coat_named",
		"legend_armor/plate/legend_southern_named_plates",
		"legend_helmets/helm/legend_helmet_barbute_named",
		"legend_helmets/helm/legend_helmet_bascinet_named",
		"legend_helmets/helm/legend_helmet_crude_skull_helm",
		"legend_helmets/helm/legend_helmet_deep_sallet_named",
		"legend_helmets/helm/legend_helmet_dentist_helmet",
		"legend_helmets/helm/legend_helmet_heavy_plate_helm_named",
		"legend_helmets/helm/legend_helmet_heavy_spiked_helm",
		"legend_helmets/helm/legend_helmet_italo_norman_helm_named",
		"legend_helmets/helm/legend_helmet_kettle_helm_named",
		"legend_helmets/helm/legend_helmet_legend_armet_01_named",
		"legend_helmets/helm/legend_helmet_legend_frogmouth_close",
		"legend_helmets/helm/legend_helmet_southern_named_conic",
		"legend_helmets/helm/legend_helmet_stag_helm",
		"legend_helmets/helm/legend_helmet_swan_helm",
		"legend_helmets/helm/legend_helmet_tailed_conic",
		"legend_helmets/helm/legend_helmet_wallace_sallet_named",
		"legend_helmets/hop/legend_helmet_bascinet_visor_named",
		"legend_helmets/hop/legend_helmet_faceplate_full_01_named",
		"legend_helmets/hop/legend_helmet_faceplate_full_gold",
		"legend_helmets/hop/legend_helmet_faceplate_gold",
		"legend_helmets/hop/legend_helmet_faceplate_raised",
		"legend_helmets/hop/legend_helmet_golden_helm",
		"legend_helmets/hop/legend_helmet_golden_mask",
		"legend_helmets/hop/legend_helmet_wallace_sallet_visor_named",
		"legend_helmets/hop/legend_helmet_warlock_skull",
	],

	EL_InValidItem = [
		"tools/acid_flask_item",
		"tools/daze_bomb_item",
		"tools/faction_banner",
		"tools/fire_bomb_item",
		"tools/holy_water_item",
		"tools/legend_broken_throwing_net",
		"tools/reinforced_throwing_net",
		"tools/smoke_bomb_item",
		"tools/throwing_net",
	],

	NegativeEffectID = [
		"effects.bleeding",
		"effects.charmed",
		"effects.chilled",
		"effects.curseofyears",
		"effects.dazed",
		"effects.debilitated",
		"effects.disarmed",
		"effects.disintegrating",
		"effects.distracted",
		"effects.hex_slave",
		"effects.horrified",
		"effects.insect_swarm",
		"effects.legend_baffled",
		"effects.legend_dazed",
		"effects.legend_demon_hound_bite_effect",
		"effects.legend_grappled",
		"effects.legend_grazed_effect",
		"effects.legend_marked_target",
		"effects.legend_parried",
		"effects.legend_redback_spider_poison",
		"effects.legend_safeguarding",
		"effects.lindwurm_acid",
		"effects.mummy_curse",
		"effects.net",
		"effects.nightmare",
		"effects.overwhelmed",
		"effects.ptr_arrow_to_the_knee_debuff",
		"effects.ptr_dented_armor",
		"effects.ptr_dismantled",
		"effects.ptr_exhausted",
		"effects.ptr_exploitable_opening",
		"effects.ptr_eyes_up",
		"effects.ptr_from_all_sides",
		"effects.ptr_intimidated",
		"effects.ptr_rattled",
		"effects.smackdown_debuff_effect",
		"effects.sweeping_strikes_debuff_effect",
		"effects.ptr_worn_down",
		"effects.rooted",
		"effects.serpent_ensnare",
		"effects.shellshocked",
		"effects.sleeping",
		"effects.spider_poison",
		"effects.staggered",
		"effects.str_covering_ally",
		"effects.stunned",
		"effects.web",
		"effects.withered",
		"effects.legend_zombie_poison",
		"effects.afraid",
		"effects.exhausted",
		"effects.hangover",
		"effects.legend_headache",
		"effects.legend_irritable",
		"el_effects.temp_weaken",
		"el_effects.weaken",
	],

	NegativeEffectScripts = [
		"scripts/skills/effects/bleeding_effect",
		"scripts/skills/effects/chilled_effect",
		"scripts/skills/effects/curseofyears_effect",
		"scripts/skills/effects/dazed_effect",
		"scripts/skills/effects/debilitated_effect",
		"scripts/skills/effects/disarmed_effect",
		"scripts/skills/effects/disintegrating_effect",
		"scripts/skills/effects/distracted_effect",
		"scripts/skills/effects/horrified_effect",
		"scripts/skills/effects/insect_swarm_effect",
		"scripts/skills/effects/legend_baffled_effect",
		"scripts/skills/effects/legend_dazed_effect",
		"scripts/skills/effects/legend_demon_hound_bite_effect",
		"scripts/skills/effects/legend_grappled_effect",
		"scripts/skills/effects/legend_grazed_effect",
		"scripts/skills/effects/legend_marked_target",
		"scripts/skills/effects/legend_redback_spider_poison_effect",
		"scripts/skills/effects/lindwurm_acid_effect",
		"scripts/skills/effects/mummy_curse_effect",
		"scripts/skills/effects/nightmare_effect",
		"scripts/skills/effects/overwhelmed_effect",
		"scripts/skills/effects/ptr_arrow_to_the_knee_debuff_effect",
		"scripts/skills/effects/ptr_dented_armor_effect",
		"scripts/skills/effects/ptr_dismantled_effect",
		"scripts/skills/effects/ptr_exhausted_effect",
		"scripts/skills/effects/ptr_eyes_up_effect",
		"scripts/skills/effects/ptr_from_all_sides_effect",
		"scripts/skills/effects/ptr_intimidated_effect",
		"scripts/skills/effects/ptr_rattled_effect",
		"scripts/skills/effects/ptr_smackdown_debuff_effect",
		"scripts/skills/effects/ptr_sweeping_strikes_debuff_effect",
		"scripts/skills/effects/ptr_worn_down_effect",
		"scripts/skills/effects/rooted_effect",
		"scripts/skills/effects/shellshocked_effect",
		"scripts/skills/effects/sleeping_effect",
		"scripts/skills/effects/spider_poison_effect",
		"scripts/skills/effects/staggered_effect",
		"scripts/skills/effects/stunned_effect",
		"scripts/skills/effects/withered_effect",
		"scripts/skills/effects/zombie_poison_effect",
		"scripts/skills/effects_world/afraid_effect",
		"scripts/skills/effects_world/exhausted_effect",
		"scripts/skills/effects_world/legend_headache_effect",
		"scripts/skills/effects_world/legend_irritable_effect",
		"scripts/skills/el_effects/el_temp_weaken_effect",
		"scripts/skills/el_effects/el_weaken_effect"
	]
};